import { StyleSheet, Dimensions } from "react-native";
import {
  FONT_FAMILY_G_REGULAR,
  FONT_FAMILY_I_REGULAR,
  ThemeColors,
} from "../../utils/Theme";

const styles: any = StyleSheet.create({
  bodyFlexStyle: {
    backgroundColor: ThemeColors.THEME_BACKGROUND_COLOR,
    width: "100%",
    margin: 0!,
    padding: 0,
    fontFamily: FONT_FAMILY_I_REGULAR,
  },

  projectListHeader: {
    paddingLeft: 12,
    marginTop: 0,
    paddingTop: 12,
    paddingRight: 12,
    marginBottom: 10,
    backgroundColor: ThemeColors.THEME_WHITE_BACKGROUND,
  },
  shoppingTitleOuter: {
    paddingLeft: 12,
    paddingTop: 12,
    paddingRight: 12,
    marginBottom: 10,
  },

  projectListOuter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  projectListInnerHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 10,
    paddingRight: 5,
    marginBottom: 10,
  },
  searchOuterBox: {
    marginTop: 10,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 0,
  },

  selectboxsaluation: {
    // marginLeft: 15,
    // marginRight: 15,
    // marginBottom: 0,
    borderWidth: 1,
    borderColor: "#F8F8F8",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
  },
  FilterOuterHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
    marginTop: 5,
    marginLeft: 12,
    marginRight: 5,
  },
  smallTextStyle: {
    color: "#000000",
    fontSize: 14,
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontWeight: "800",
    lineHeight: 20,
  },
  BlockWhite: {
    marginTop: 0,
    marginLeft: 18,
    marginRight: 18,
    marginBottom: 18,
    backgroundColor: ThemeColors.THEME_WHITE_BACKGROUND,
    borderRadius: 5,
    paddingBottom: 20,
  },
  productStyle: {
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 15,
  },
  smallTextPara: {
    color: "#000000",
    fontSize: 18,
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontWeight: "800",
    lineHeight: 20,
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 12,
    paddingBottom: 0,
  },
  productNumber: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 5,
    paddingRight: 5,
    paddingTop: 0,
  },
  productPara: {
    color: "#757575",
    fontSize: 12,
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontWeight: "600",
    lineHeight: 20,
  },
  roundButton: {
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 30,
    backgroundColor: "#000000",
  },
  roundBlackButton: {
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 30,
    marginTop: 2,
    backgroundColor: "#000000",
  },
  whiteText: {
    color: "#FFFFFF",
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  shoppinglistOuter: {
    flexDirection: "row",
    paddingTop: 10,
    alignItems: "center",
  },
  shoppinglistInner: {
    flexDirection: "row",
    alignItems: "center",
  },
  shoppinglistPara: {
    color: "#000000",
    fontSize: 12,
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontWeight: "600",
    lineHeight: 20,
  },
  orangeBoxDiv: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 5,
    margin: 10,
    backgroundColor: "rgba(239, 127, 0, 0.1)",
  },
  orangetext: {
    color: "#E65100",
    fontSize: 12,
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontWeight: "800",
    lineHeight: 20,
  },
  pinkBoxDiv: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 5,
    margin: 10,
    backgroundColor: "rgba(204, 51, 51, 0.1)",
  },
  redtext: {
    color: "#CC3333",
    fontSize: 12,
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontWeight: "800",
    lineHeight: 20,
  },

  showText: {
    color: "#000000",
    fontSize: 12,
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontWeight: "600",
    lineHeight: 20,
    textDecorationLine: "underline",
  },

  whiteBoxDiv: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
    marginTop: 0,
    margin: 15,

    // borderWidth: 1,
    // borderColor: "#DDDBDA",
    backgroundColor: "#FFFFFF",
  },
  whiteOuterDiv: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 15,

    marginTop: 10,
    marginBottom: 10,

    // borderWidth: 1,
    // borderColor: "#DDDBDA",
    backgroundColor: "#FFFFFF",
  },
  darkGrayText: {
    color: "#757575",
  },
  // Counter

  decrementButton: {
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    // borderColor: '#E3E7ED',
    // borderWidth: 0.5,
    // backgroundColor: '#FFFFFF',
  },
  incrementButton: {
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    // borderColor: '#E3E7ED',
    // borderWidth: 0.5,
    // backgroundColor: '#FFFFFF',
  },
  incrementDecrementButtons: {
    width: 35,
    height: 35,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderColor: "#B3B3B3",
    borderWidth: 0.8,
  },
  incrementDecrementOuter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 10,
  },
  incrementDecrementtextOuter: {
    width: 55,
    height: 35,
    borderColor: "#B3B3B3",
    borderTopWidth: 1,
    borderBottomWidth: 0.8,
    alignItems: "center",
    justifyContent: "center",
  },
  incrementDecrementtext: {
    fontFamily: FONT_FAMILY_G_REGULAR,
    fontSize: 16,
    fontWeight: "400",
    color: "#313131",
    textAlign: "center",
  },
  incrementDecrementButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#242424",
  },

  roundGrayButton: {
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 15,
    paddingBottom: 15,
    borderRadius: 30,
    backgroundColor: "#B3B3B3",
  },
  grayText: {
    color: "#000000",
    fontFamily: FONT_FAMILY_G_REGULAR,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  viewBtnStyle: {
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 15,
    margin: 20,
  },

  roundWhiteButton: {
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 15,
    paddingBottom: 15,
    borderRadius: 30,
    backgroundColor: "#FFFFFF",
  },

  selectItemInner: {
    flexDirection: "row",
    gap: 15,
    alignItems: "center",
  },

  gapStyle: {
    margin: 5,
  },
  gapFlexStyle: {
    margin: 10,
  },
  gapRightLeftFlexStyle: {
    marginLeft: 60,
  },
  shoppinglisttxt: {
    color: "#000000",
    fontFamily: FONT_FAMILY_G_REGULAR,
    fontSize: 16,
    fontWeight: "600",
  },
  dateTxt: {
    color: "#757575",
    fontFamily: FONT_FAMILY_G_REGULAR,
    fontSize: 14,
    fontWeight: "400",
  },
  datedarkTxt: {
    color: "#000000",
    fontFamily: FONT_FAMILY_G_REGULAR,
    fontSize: 14,
    fontWeight: "400",
  },
  borderbottom: {
    borderBottomWidth: 1,
    borderBottomColor: "#DDDBDA",
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 0,
    paddingRight: 0,
  },
  buttonWrapper: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 20,
    marginTop: 30,
  },
  cancelModalBtn: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 25,
    paddingRight: 25,
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 25,
    backgroundColor: "#ffffff",
    marginRight: 10,
  },
  cancelTicketTxt: {
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontSize: 14,
    fontWeight: "700",
    color: "#000000",
    letterSpacing: 0.42,
    textAlign: "center",
  },
  continueModalBtn: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 65,
    paddingRight: 65,
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 25,
    backgroundColor: "#ffffff",
    marginRight: 10,
  },
  continueTicketTxt: {
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontSize: 14,
    fontWeight: "700",
    color: "#000000",
    letterSpacing: 0.42,
    textAlign: "center",
  },
  confirmBtn: {
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 30,
    paddingRight: 30,
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 25,
    backgroundColor: "#000000",
  },
  addAllBtn: {
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 65,
    paddingRight: 65,
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 25,
    backgroundColor: "#000000",
  },
  rescheduleTxt: {
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontSize: 14,
    fontWeight: "700",
    color: "#ffffff",
    textAlign: "center",
    letterSpacing: 0.42,
  },
  reasonTxt: {
    fontSize: 12,
    fontFamily: FONT_FAMILY_I_REGULAR,
    letterSpacing: 0.12,
    marginBottom: 10,
    color: "#000000",
    fontWeight: "400",
  },
  addNewTitle: {
    fontFamily: FONT_FAMILY_I_REGULAR,
    fontSize: 16,
    fontWeight: "600",
    color: "#000000",
    letterSpacing: -0.9,
    textAlign: "center",
  },
  cancelModalMainWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  cancelTicketHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 10,
    width: "95%",
  },
  closeIcon: {
    // backgroundColor:"green",
    marginLeft: 20,
    width: 10,
    height: 10,
  },
  input: {
    height: 30,
    borderWidth: 1,
    padding: 5,
    borderRadius: 5,
    borderColor: "#DDDBDA",
    fontSize: 16,
    marginBottom: 10,
    // backgroundColor: "#F8F8F8"
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: "flex-start",
    marginVertical: 8,
    paddingLeft: 0,
    paddingRight: 0,
    marginBottom: 0,
  },
  checkBoxText: {
    fontSize: 16,
    fontWeight: "400",
    color: "#000000",
  },
  textInputContainer: {
    marginBottom: 10,
    borderRadius: 4,
    backgroundColor: "#ffffff",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
    paddingBottom: 20,
    maxHeight: (Dimensions.get("window").height * 70) / 100,
    minHeight: 50,
    color: "#01182D",
    fontFamily: "Gilroy-Normal",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#e9ebef",
  },
  shoppingTitleStyle: {
    fontSize: 30,
    fontWeight: "600",
    color: "#000000",
  },
  shoppingTitleParaStyle: {
    fontSize: 14,
    fontWeight: "400",
    color: "#000000",
    padding: 5,
  },

  productInfoWrapper: {
    width: "100%",
    flexDirection: "row",

    padding: 8,
    marginBottom: 5,
    // backgroundColor:"yellow"
  },
  productImg: {
    width: 80,
    height: 80,
    marginRight: 20,
  },

  productInfoRight: {
    flexWrap: "wrap",
    // paddingRight:15,
  },

  orderTitle: {
    fontWeight: "bold",
    fontSize: 14,
    color: "#000000",
  },

  skuMainWrapper: {
    flexDirection: "row",
  },
  skuWrapper: {
    flexDirection: "row",
    alignItems: "center",
  },
  upcWrapper: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 18,
  },
  sectionSeperator: {
    marginLeft: 19,
    fontSize: 18,
  },
  skuTxt: {
    fontSize: 12,
  },
  skuNo: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#000000",
  },
  deletetitle: {
    fontSize: 14,
    color: "#000000",
    fontWeight: "400",
  },
  txtCenter: {
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "center",
    padding: 10,
  },
  shoppingProductNumber: {
    flexDirection: "row",
    alignItems: "center",
  },
});

export default styles;
